### ISSUE TITLE
ENOENT, no such file or directory

### ISSUE THREAD

**Issue by PDXIII** [huafu/ember-google-map#10]
Hi!

When I try to integrate your add-on via npm, I always receive the same error:

    File: huw-mcv/controllers/application.js
    ENOENT, no such file or directory '/Users/PATHTOPROJECT/HUW-MCV/tmp/tree_merger-tmp_dest_dir-rhkm4PNw.tmp/ember-google-map/components/google-map.js'
    Error: ENOENT, no such file or directory '/Users/PATHTOPROJECT/HUW-MCV/tmp/tree_merger-tmp_dest_dir-rhkm4PNw.tmp/ember-google-map/components/google-map.js'
        at Object.fs.statSync (fs.js:695:18)
        at addModule (/Users/PATHTOPROJECT/HUW-MCV/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:94:46)
        at addModule (/Users/PATHTOPROJECT/HUW-MCV/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:143:9)
        at /Users/PATHTOPROJECT/HUW-MCV/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:59:7
        at $$$internal$$tryCatch (/Users/PATHTOPROJECT/HUW-MCV/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
        at $$$internal$$invokeCallback (/Users/PATHTOPROJECT/HUW-MCV/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
        at $$$internal$$publish (/Users/PATHTOPROJECT/HUW-MCV/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
        at $$rsvp$asap$$flush (/Users/PATHTOPROJECT/HUW-MCV/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
        at process._tickCallback (node.js:419:13)

I changed the import path from ```google-map``` to ```ember-google-map``` as you can see, but I can’t get it running.

**Comment by huafu** [comment]
Ok I've fixed that in the README too, lemme know if you have anymore issue

**Comment by PDXIII** [comment]
That's great!

**Comment by PDXIII** [comment]
The map works fine now, but the syntax for Ember.select has changed in the last update. And maybe you need to tell people, that they need to give ´´´.map-canvas```some height.

    .map-canvas {
      position: relative;
      height: 100%;
      width: 100%;
    }

But non the less: this is a great add-on. And when I am allowed to vote for an feature: Styles.
Maybe, when this all starts to make sense to me, I’ll provide you a PR, but I right now I am a total n00b to Ember!
