### ISSUE TITLE
dynamically re-rendering the map component

### ISSUE THREAD

**Issue by cgencer** [huafu/ember-google-map#94]
Is it possible to re-render the component trough an action or event triggered by the controller?

**Comment by huafu** [comment]
The goal of the component is to use ember bindings so that anytime you change any property of the component or any of its markers, circles, etc... it'll update the map or marker, etc... So I am not sure why you want to re-render

**Comment by cgencer** [comment]
ok it was my bad, i've used a previous version of ember, which ember-cli directly installed. 
then i tried now to first create a clean working copy of your example page, first with sane/sails then with only ember-cli. i tried 1.9.1 as ember version (where your example also runs on the same version), which gave some template engine trouble:
File: modules/ember-cli-app-version/templates/app-version.hbs
Unexpected token ,
SyntaxError: Unexpected token ,
    at Object.Function (native)
    at Object.createFunctionContext (/Users/obsesif/worx/tuiyo/tufor/client/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23)
    at Object.compile (/Users/obsesif/worx/tuiyo/tufor/client/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:142:19)
    at Object.EmberHandlebars.precompile (/Users/obsesif/worx/tuiyo/tufor/client/bower_components/ember/ember-template-compiler.js:294:51)
    at Object.module.exports.template (/Users/obsesif/worx/tuiyo/tufor/client/node_modules/ember-cli-htmlbars/utils.js:29:40)
    at TemplateCompiler.processString (/Users/obsesif/worx/tuiyo/tufor/client/node_modules/ember-cli-htmlbars/index.js:55:36)
    at TemplateCompiler.Filter.processFile (/Users/obsesif/worx/tuiyo/tufor/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/index.js:136:31)
    at /Users/obsesif/worx/tuiyo/tufor/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/index.js:85:21
    at lib$rsvp$$internal$$tryCatch (/Users/obsesif/worx/tuiyo/tufor/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/obsesif/worx/tuiyo/tufor/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:505:17)

then i tried to fall-back ember versions, until 1.4-1.5, all gave the same error with broccoli, template compiler etc. i also tried 2.0 and 2.1 versions which gave error on {{view}} pathing.

i'd be glad if you can share only the example folder structure, with its specific versions for node_modules and bower_components.

i also try to combine this with simple_auth, passpor and torii and also maybe even dare to try it with ember 2+.i guess google-map also needs a rewrite for 2+ as well. any plans?
thanks!

**Comment by cgencer** [comment]
the 2.1 error is:
Assertion Failed: Using `{{view}}` or any path based on it ('secretcodez/templates/components/google-map.hbs' @ L5:C6) has been removed in Ember 2.0
